psql -c "CREATE DATABASE pm_app_dev;"
psql -c "CREATE USER pm_app_dev WITH PASSWORD 'test';"
psql -c "ALTER DATABASE pm_app_dev OWNER to pm_app_dev;"
psql -c "GRANT ALL PRIVILEGES ON DATABASE pm_app_dev to pm_app_dev;"
psql -c "CREATE DATABASE pm_app_test;"
psql -c "CREATE USER pm_app_test WITH PASSWORD 'test';"
psql -c "ALTER DATABASE pm_app_test OWNER to pm_app_test;"
psql -c "GRANT ALL PRIVILEGES ON DATABASE pm_app_test to pm_app_test;"
psql -c "ALTER USER pm_app_test CREATEDB;"
